
package com.sheerimagination.businessobject.fulfillment.fsi.inventory.api;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Inventory", targetNamespace = "http://www.fsicatalog.com/Webservices/", wsdlLocation = "file:fsi.inventory.wsdl")
public class Inventory
    extends Service
{

    private final static URL INVENTORY_WSDL_LOCATION;
    private final static WebServiceException INVENTORY_EXCEPTION;
    private final static QName INVENTORY_QNAME = new QName("http://www.fsicatalog.com/Webservices/", "Inventory");

    static {
        INVENTORY_WSDL_LOCATION = com.sheerimagination.businessobject.fulfillment.fsi.inventory.api.Inventory.class.getResource("file:fsi.inventory.wsdl");
        WebServiceException e = null;
        if (INVENTORY_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'file:fsi.inventory.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        INVENTORY_EXCEPTION = e;
    }

    public Inventory() {
        super(__getWsdlLocation(), INVENTORY_QNAME);
    }

    public Inventory(WebServiceFeature... features) {
        super(__getWsdlLocation(), INVENTORY_QNAME, features);
    }

    public Inventory(URL wsdlLocation) {
        super(wsdlLocation, INVENTORY_QNAME);
    }

    public Inventory(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INVENTORY_QNAME, features);
    }

    public Inventory(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Inventory(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InventorySoap
     */
    @WebEndpoint(name = "InventorySoap")
    public InventorySoap getInventorySoap() {
        return super.getPort(new QName("http://www.fsicatalog.com/Webservices/", "InventorySoap"), InventorySoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InventorySoap
     */
    @WebEndpoint(name = "InventorySoap")
    public InventorySoap getInventorySoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.fsicatalog.com/Webservices/", "InventorySoap"), InventorySoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INVENTORY_EXCEPTION!= null) {
            throw INVENTORY_EXCEPTION;
        }
        return INVENTORY_WSDL_LOCATION;
    }

}
