
package com.sheerimagination.businessobject.fulfillment.fsi.inventory.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InventorySoap", targetNamespace = "http://www.fsicatalog.com/Webservices/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InventorySoap {


    /**
     * 
     * @param inventoryRequest
     * @return
     *     returns com.sheerimagination.businessobject.fulfillment.fsi.inventory.api.InventoryReply
     */
    @WebMethod(operationName = "InventoryInquiry", action = "http://www.fsicatalog.com/Webservices/InventoryInquiry")
    @WebResult(name = "InventoryReply", targetNamespace = "https://www.fsicatalog.com/WebServices")
    @RequestWrapper(localName = "InventoryInquiry", targetNamespace = "http://www.fsicatalog.com/Webservices/", className = "com.sheerimagination.businessobject.fulfillment.fsi.inventory.api.InventoryInquiry")
    @ResponseWrapper(localName = "InventoryInquiryResponse", targetNamespace = "http://www.fsicatalog.com/Webservices/", className = "com.sheerimagination.businessobject.fulfillment.fsi.inventory.api.InventoryInquiryResponse")
    public InventoryReply inventoryInquiry(
        @WebParam(name = "InventoryRequest", targetNamespace = "https://www.fsicatalog.com/WebServices")
        InventoryRequest inventoryRequest);

}
