
package com.sheerimagination.businessobject.fulfillment.fsi.orderstatus.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IOrdersContract", targetNamespace = "http://tempuri.org/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IOrdersContract {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.sheerimagination.businessobject.fulfillment.fsi.orderstatus.api.OrderResponse
     */
    @WebMethod(operationName = "ProcessOrder", action = "https://www.fsicatalog.com/services/orderprocessing/v4/OrdersContract/ProcessOrder")
    @WebResult(name = "OrderResponse", targetNamespace = "https://www.fsicatalog.com/services/orderprocessing/v4", partName = "parameters")
    public OrderResponse processOrder(
        @WebParam(name = "OrderRequest", targetNamespace = "https://www.fsicatalog.com/services/orderprocessing/v4", partName = "parameters")
        OrderRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.sheerimagination.businessobject.fulfillment.fsi.orderstatus.api.StatusResponse
     */
    @WebMethod(operationName = "GetServiceStatus", action = "https://www.fsicatalog.com/services/orderprocessing/v4/OrdersContract/GetServiceStatus")
    @WebResult(name = "StatusResponse", targetNamespace = "https://www.fsicatalog.com/services/orderprocessing/v4", partName = "parameters")
    public StatusResponse getServiceStatus(
        @WebParam(name = "StatusRequest", targetNamespace = "https://www.fsicatalog.com/services/orderprocessing/v4", partName = "parameters")
        StatusRequest parameters);

}
