
package com.sheerimagination.businessobject.fulfillment.fsi.orderstatus.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OrderStatusContract", targetNamespace = "https://www.fsicatalog.com/services/OrderStatus/v2")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OrderStatusContract {


    /**
     * 
     * @param request
     * @return
     *     returns com.sheerimagination.businessobject.fulfillment.fsi.orderstatus.api.OrderStatusReply
     */
    @WebMethod(operationName = "GetOrderStatus", action = "https://www.fsicatalog.com/services/OrderStatus/v2/OrderStatusContract/GetOrderStatus")
    @WebResult(name = "GetOrderStatusResult", targetNamespace = "https://www.fsicatalog.com/services/OrderStatus/v2")
    @RequestWrapper(localName = "GetOrderStatus", targetNamespace = "https://www.fsicatalog.com/services/OrderStatus/v2", className = "com.sheerimagination.businessobject.fulfillment.fsi.orderstatus.api.GetOrderStatus")
    @ResponseWrapper(localName = "GetOrderStatusResponse", targetNamespace = "https://www.fsicatalog.com/services/OrderStatus/v2", className = "com.sheerimagination.businessobject.fulfillment.fsi.orderstatus.api.GetOrderStatusResponse")
    public OrderStatusReply getOrderStatus(
        @WebParam(name = "request", targetNamespace = "https://www.fsicatalog.com/services/OrderStatus/v2")
        OrderStatusRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.sheerimagination.businessobject.fulfillment.fsi.orderstatus.api.OrderStatusReply
     */
    @WebMethod(operationName = "GetOrderStatusJson", action = "https://www.fsicatalog.com/services/OrderStatus/v2/OrderStatusContract/GetOrderStatusJson")
    @WebResult(name = "GetOrderStatusJsonResult", targetNamespace = "https://www.fsicatalog.com/services/OrderStatus/v2")
    @RequestWrapper(localName = "GetOrderStatusJson", targetNamespace = "https://www.fsicatalog.com/services/OrderStatus/v2", className = "com.sheerimagination.businessobject.fulfillment.fsi.orderstatus.api.GetOrderStatusJson")
    @ResponseWrapper(localName = "GetOrderStatusJsonResponse", targetNamespace = "https://www.fsicatalog.com/services/OrderStatus/v2", className = "com.sheerimagination.businessobject.fulfillment.fsi.orderstatus.api.GetOrderStatusJsonResponse")
    public OrderStatusReply getOrderStatusJson(
        @WebParam(name = "request", targetNamespace = "https://www.fsicatalog.com/services/OrderStatus/v2")
        OrderStatusRequest request);

}
