
package com.sheerimagination.businessobject.fulfillment.fsi.orderstatus.api;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Orders", targetNamespace = "http://tempuri.org/", wsdlLocation = "file:/D:/Work/Repos/fsi-client/wsdl/fsi.orders.wsdl")
public class Orders
    extends Service
{

    private final static URL ORDERS_WSDL_LOCATION;
    private final static WebServiceException ORDERS_EXCEPTION;
    private final static QName ORDERS_QNAME = new QName("http://tempuri.org/", "Orders");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/Work/Repos/fsi-client/wsdl/fsi.orders.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ORDERS_WSDL_LOCATION = url;
        ORDERS_EXCEPTION = e;
    }

    public Orders() {
        super(__getWsdlLocation(), ORDERS_QNAME);
    }

    public Orders(WebServiceFeature... features) {
        super(__getWsdlLocation(), ORDERS_QNAME, features);
    }

    public Orders(URL wsdlLocation) {
        super(wsdlLocation, ORDERS_QNAME);
    }

    public Orders(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ORDERS_QNAME, features);
    }

    public Orders(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Orders(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IOrdersContract
     */
    @WebEndpoint(name = "OrdersEndpointSoap11")
    public IOrdersContract getOrdersEndpointSoap11() {
        return super.getPort(new QName("http://tempuri.org/", "OrdersEndpointSoap11"), IOrdersContract.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IOrdersContract
     */
    @WebEndpoint(name = "OrdersEndpointSoap11")
    public IOrdersContract getOrdersEndpointSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "OrdersEndpointSoap11"), IOrdersContract.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ORDERS_EXCEPTION!= null) {
            throw ORDERS_EXCEPTION;
        }
        return ORDERS_WSDL_LOCATION;
    }

}
