
package com.sheerimagination.businessobject.fulfillment.fsi.orderstatus.api;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OrderStatus", targetNamespace = "https://www.fsicatalog.com/services/OrderStatus/v2", wsdlLocation = "file:fsi.order.status.wsdl")
public class OrderStatus
    extends Service
{

    private final static URL ORDERSTATUS_WSDL_LOCATION;
    private final static WebServiceException ORDERSTATUS_EXCEPTION;
    private final static QName ORDERSTATUS_QNAME = new QName("https://www.fsicatalog.com/services/OrderStatus/v2", "OrderStatus");

    static {
        ORDERSTATUS_WSDL_LOCATION = com.sheerimagination.businessobject.fulfillment.fsi.orderstatus.api.OrderStatus.class.getResource("file:fsi.order.status.wsdl");
        WebServiceException e = null;
        if (ORDERSTATUS_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'file:fsi.order.status.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        ORDERSTATUS_EXCEPTION = e;
    }

    public OrderStatus() {
        super(__getWsdlLocation(), ORDERSTATUS_QNAME);
    }

    public OrderStatus(WebServiceFeature... features) {
        super(__getWsdlLocation(), ORDERSTATUS_QNAME, features);
    }

    public OrderStatus(URL wsdlLocation) {
        super(wsdlLocation, ORDERSTATUS_QNAME);
    }

    public OrderStatus(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ORDERSTATUS_QNAME, features);
    }

    public OrderStatus(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderStatus(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OrderStatusContract
     */
    @WebEndpoint(name = "SoapEndPoint")
    public OrderStatusContract getSoapEndPoint() {
        return super.getPort(new QName("https://www.fsicatalog.com/services/OrderStatus/v2", "SoapEndPoint"), OrderStatusContract.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderStatusContract
     */
    @WebEndpoint(name = "SoapEndPoint")
    public OrderStatusContract getSoapEndPoint(WebServiceFeature... features) {
        return super.getPort(new QName("https://www.fsicatalog.com/services/OrderStatus/v2", "SoapEndPoint"), OrderStatusContract.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ORDERSTATUS_EXCEPTION!= null) {
            throw ORDERSTATUS_EXCEPTION;
        }
        return ORDERSTATUS_WSDL_LOCATION;
    }

}
